# Generated by Django 5.0.6 on 2024-05-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='../default_img.jpg', upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='18:00'),
        ),
    ]
