# Generated by Django 5.0.6 on 2024-05-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image_event_location_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default='18:00'),
        ),
    ]
