# Generated by Django 5.0.6 on 2024-05-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default_img.jpg', upload_to='event_images/'),
        ),
    ]
